### ISSUE TITLE
使用context-path配置后接口文档无法访问

### ISSUE THREAD

**Issue by ljw0903** [liuanxin/api-document#3]
![image](https://user-images.githubusercontent.com/42686420/97141859-8644f280-179a-11eb-99c7-a0b44b8c93ab.png)
在配置中没发现在哪里设置前缀

**Comment by liuanxin** [comment]
目前基于二级目录的配置还没有, 前端页面对后台接口是没有强依赖的, 也就是你如果直接将页面的源码保存到本地, 用浏览器打开也是可以的([比如](https://liuanxin.github.io/api-info.html)). 因为要请求到 `/api/info` 后才能获取到后台的配置, 这存在一个先有蛋还是先有鸡的问题, 如果要实现这点, 得弹出输入框让用户输入后保存到本地, 我个人感觉这并不是一个好的体检

**Comment by liuanxin** [comment]
@ljw0903 可以使用 0.7.8 的版本
```xml
<dependency>
  <groupId>com.github.liuanxin</groupId>
  <artifactId>api-document</artifactId>
  <version>0.7.8</version>
</dependency>
```

如果失败, 可以在页面上设置请求前缀
![image](https://user-images.githubusercontent.com/2647495/97287162-355afa00-187f-11eb-89f3-e33190554078.png)

你最初的问题输入 `127.0.0.1:8080/MS6000` 即可

**Comment by ljw0903** [comment]
好的 感谢~
